import type { IForm } from "../types";

export const initialState: IForm = {
  jobTitle: "",
  companyName: "",
  location: "",
  jobType: "",
  workSetting: "",
  experienceLevel: "",
  employmentType: "",
  duration: "",
  durationUnit: "",
  salaryMin: "",
  salaryMax: "",
  applicationDeadline: "",
  jobDescription: "",
  requirements: [],
  skills: [],
  benefits: [],
  keyResponsibilities: [],
  status: "",
  createdAt: "",
  email: "",
  applicationsCount: 0,
};
